services:
  # A Web Service for your Next.js frontend
  - type: web
    name: my-interview-platform
    env: node
    plan: free
    buildCommand: 'npm install && npm run build'
    startCommand: 'npm start'
    healthCheckPath: /
    envVars:
      - key: MONGODB_URI # This will be set manually in the Render dashboard
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JUDGE0_API_KEY
        sync: false
      - key: JUDGE0_API_HOST
        sync: false
      - key: NODE_ENV
        value: production